services:
  rag-app:
    image: maxenceleguery/enstrag-server:latest
    #build:
    #  dockerfile: ./Dockerfile
    
    container_name: rag-app
    command: ["condapython3", "-m", "enstrag", "--local", "--server", "--persist_dir", "/app/vector_db", "--models_path", "/app/weights"]
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - /home/student/weights:/app/weights
      - /home/student/vector_db:/app/vector_db
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  front:
    image: maxenceleguery/enstrag-front:latest
    #build: 
    #  dockerfile: /home/student/enstrag/Dockerfilefront
    depends_on:
      - rag-app
    ports:
      - "7861:7861"
    networks:
      - my_network
    volumes:
      - /home/student/vector_db:/app/vector_db
    environment:
      - API_URL=http://rag-app:8000
      - PERSIST_PATH=/app/vector_db

    restart: unless-stopped

networks:
  my_network:
    driver: bridge